# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from serial_com import *
##################
#####串口初始化#####
port = "COM1"
rate = 115200
ser=serial_init(port,rate)

print("-----串口初始化--------")
##################
class Ui_MainWindow(object):
    # 默认值 串口
    com='1'
    # 默认值 距离
    dis='0'
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_2.addWidget(self.pushButton_run)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.spinbox_com = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_com.setMinimum(1)
        self.spinbox_com.setMaximum(3)
        self.spinbox_com.setObjectName("spinbox_com")
        self.horizontalLayout_3.addWidget(self.spinbox_com)
        self.pushButton_cut = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cut.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_cut.setObjectName("pushButton_cut")
        self.horizontalLayout_3.addWidget(self.pushButton_cut)
        self.lineEdit_dis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dis.setObjectName("lineEdit_dis")
        self.horizontalLayout_3.addWidget(self.lineEdit_dis)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.lineEdit_dis.editingFinished.connect(self.ReadText)
        self.pushButton_cut.clicked.connect(self.RunCut)
        self.pushButton_run.clicked.connect(self.StartRun)
        self.spinbox_com.valueChanged['QString'].connect(self.ReadCom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_cut.setText(_translate("MainWindow", "Go"))
        self.menu.setTitle(_translate("MainWindow", "stetting"))

    def StartRun(self):
        message=self.com+"OR\r\n"
        print(message)
        senddata(message,ser)
    def ReadText(self):
        self.dis=self.lineEdit_dis.text()
        print("移动距离为"+self.dis)
        return self.dis
    def ReadCom(self):
        self.com=self.spinbox_com.text()
        print("电机编号为"+self.com)
        return self.com
    def RunCut(self):
        message=self.com+"PA"+self.dis+'\r\n'
        print(message)
        senddata(message,ser)
