# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys,cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from ClassSer import *

class Ui_MainWindow(object):
    def __init__(self):
        self.setupUi(MainWindow)
        self.timer = QtCore.QTimer()
        self.connect_pushbutton()
        self.cap_video = 0
        self.flag = 0
        self.img = []
        self.CameraNum='0'
        self.MotorNum = '1'
        self.dis = '0'
        self.ser=serial_port()
    def connect_pushbutton(self):
        self.timer.timeout.connect(self.show_viedo)
        self.pushButton_Camera.clicked.connect(self.video_button)
        self.Camrea_select.valueChanged['QString'].connect(self.ReadCamera)  # 相机选择
        self.pushButton_run.clicked.connect(self.StartRun) # 电机初试化
        self.Motor_select.valueChanged['QString'].connect(self.ReadMotorNum) # 电机选择
        self.dis_input.editingFinished.connect(self.ReadText)
        self.pushButton_running.clicked.connect(self.RunCut)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 627)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget= QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 351, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_Camrea = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_Camrea.setStyleSheet("background-color: rgb(172, 171, 171);")
        self.Label_Camrea.setText("")
        self.Label_Camrea.setObjectName("Label_Camrea")
        self.gridLayout.addWidget(self.Label_Camrea, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 310, 161, 50))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_Camera = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_Camera.setObjectName("pushButton_Camera")
        self.gridLayout_2.addWidget(self.pushButton_Camera, 0, 3, 1, 1)
        self.Camrea_select = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.Camrea_select.setObjectName("Camrea_select")
        self.gridLayout_2.addWidget(self.Camrea_select, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 370, 160, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_run = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout.addWidget(self.pushButton_run)
        self.pushButton_stop = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 400, 111, 101))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_running = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_running.setObjectName("pushButton_running")
        self.gridLayout_4.addWidget(self.pushButton_running, 3, 0, 1, 1)
        self.Motor_select = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.Motor_select.setObjectName("Motor_select")
        self.Motor_select.setMinimum(1)
        self.Motor_select.setMaximum(3)
        self.gridLayout_4.addWidget(self.Motor_select, 0, 0, 1, 1)
        self.dis_input = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.dis_input.setObjectName("dis_input")
        self.gridLayout_4.addWidget(self.dis_input, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        # self.pushButton_Camera.clicked.connect(self.video_button)
        # self.timer.timeout.connect(self.show_viedo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Camera.setText(_translate("MainWindow", "OPEN"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_running.setText(_translate("MainWindow", "Go"))
    def video_button(self):
        if (self.flag == 0):
            self.cap_video = cv2.VideoCapture(int(self.CameraNum))
            self.timer.start(10)
            self.flag += 1
            self.pushButton_Camera.setText("Close")
        else:
            self.timer.stop()
            self.cap_video.release()
            self.Label_Camrea.clear()
            self.pushButton_Camera.setText("Open")
            self.flag = 0
    def show_viedo(self):
        ret, self.img = self.cap_video.read()
        if ret:
            self.show_cv_img(self.img)
    def show_cv_img(self, img):
        shrink = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        QtImg = QtGui.QImage(shrink.data,
                             shrink.shape[1],
                             shrink.shape[0],
                             shrink.shape[1] * 3,
                             QtGui.QImage.Format_RGB888)
        jpg_out = QtGui.QPixmap(QtImg).scaled(
            self.Label_Camrea.width(), self.Label_Camrea.height())

        self.Label_Camrea.setPixmap(jpg_out)
    def ReadCamera(self):
        self.CameraNum=self.Camrea_select.text()
        print("相机编号为"+self.CameraNum)
    def StartRun(self):
        self.ser.send=self.MotorNum+"OR\r\n"
        print(self.ser.send)
        self.ser.senddata()
    def ReadText(self):
        self.dis=self.dis_input.text()
        print("移动距离为"+self.dis)
        return self.dis
    def ReadMotorNum(self):
        self.MotorNum=self.Motor_select.text()
        print("电机编号为"+self.MotorNum)
    def RunCut(self):
        self.ser.send=self.MotorNum+"PA"+self.dis+'\r\n'
        print(self.ser.send)
        self.ser.senddata()
if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())